title: "Lost in Thoughts"
author: "Ruu Hsu"
description: "Ph.D. student in Genetics; Based in Houston, TX"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false      # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "blog.md", "Blog"}
  - {title: "Lab", url: "https://www.bcm.edu/research/faculty-labs/philip-lupo-lab"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:Ching-Ju.Hsu@bcm.edu"}
  - {title: Github, icon: github, url: "https://github.com/ruuhsu"}
  - {title: Subscribe, icon: rss, url: "https://www.linkedin.com/in/ruuhsu/"}


comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
